language: php

notifications:
  email:
    - danhanly@gmail.com

php:
  - 5.5
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
